### ISSUE TITLE
第二周idea提交0401 已确定

### ISSUE THREAD

**Issue by Rebecca19** [Rebecca19/FeiWenTianTuan#15]
最终确定：
月可支配收入小于5000块，周末无聊，个人无兴趣爱好，想尝试不同的生活内容的用户，在晚上 周末等闲暇时间
使用我们设计的【线上生活兴趣课程】可以很好解决用户无聊、不知道如何支配闲暇时间，让生活变得不枯燥和变得有趣的问题
面临的挑战有
1.内容来源、用户体验、展现交互形式
2.和线下活动课的差异化点在哪里，万一大号做了怎么办？
3.服务形式：社群or线下
4.首次体验好，创新点？？？的挑战~

宏玉一个点子：可以用星座界面，12星座推进不同的课程等内容，吸引用户进入

关键词：
1.考虑是不是知识付费，一定要是知识付费
2.不能是单纯的课程（比如100天怎么样）

idea5.中老年人在线学习平台（有市场，但感觉盈利的可能性不大）
idea7.专门服务孕期女性或者待孕女性的知识付费平台
只服务于这个人群，包括夫妻关系处理、婆媳关系处理等

idea8.编剧同盟平台（重点服务于编剧工作者）
有编剧写作课程，编剧招聘（工作室招聘），大神专区，曝光专区

idea9.野外生存小程序
用户分享一切关于野外生存的必备技能，可以是视频，音频，图片，文字
分区域（如何吃饭，如何寻找睡觉地点，如何避免野外危险）

idea10.女子防身小程序
关于日常防身，防身术，如何察觉有迹象的跟踪等等。

**Comment by zhaozehua2018** [comment]
![image](https://user-images.githubusercontent.com/37840101/38171052-21707a74-35c4-11e8-80b4-aa2ecf1b15de.png)
知识共享平台：
用户路径：
付费-->买课-->共享账号

扩展路径：
共享一个账号的同学，进群群聊，聊问题。

**Comment by Rebecca19** [comment]
![](https://ws2.sinaimg.cn/large/006tNc79ly1fpx7dbaj3gj31kw0vlk9e.jpg)
 昨晚的拆分。几个问题：

1.为啥不打开电视直接看电视节目呢？要用手机链接电视的方式？
2.老年人的需求有多大？是不是很多线下爱心帮助足以解决？

## 行业报告

[中国互联网居家养老服务专题分析2017](https://www.analysys.cn/analysis/trade/detail/1000997/)
[OMD：重找自我的新一代老年人（附报告下载） | 互联网数据中心-199IT | 中文互联网数据研究资讯中心-199IT](http://www.199it.com/archives/618773.html)

## 几个游戏角色app

先占个坑，找到放上
