### ISSUE TITLE
我们第二周的DDL，大家一定要仔细看哦！

### ISSUE THREAD

**Issue by Rebecca19** [Rebecca19/FeiWenTianTuan#19]
![](https://ws3.sinaimg.cn/large/006tNc79ly1fq0pg1m6ajj30sg0qutdf.jpg)

任务拆分：

4月3日团队着手去做：
产品demo——泽华
落地页—— 一锋

行业分析报告：
总体框架——彭彭
竞品分析1个+用户故事1个——晓杰（可机动配合）
竞品分析1个+用户调研方案——宏玉 
用户故事1个+优化——琼月

4月4日 晚10点，提交组内初稿，讨论优化。（demo+落地页+行业分析报告）

关于用户调研
注意：由于本次用研数量翻倍，我们需要提前准备。
，
4月4日晚上10点之前，宏玉需出用户调研方案，以确保大家有时间去调研翻倍数量的用户。

4月4日-4月6日，每人获取精准用户信息10个，分别调研用户4个。
宏玉重点是出用户调研报告，所以调研用户可机动，随时和大家沟通。

**Comment by annyeat** [comment]
4月7日中午12点前，提交用户调研报告第一版，小组讨论。
            晚上继续优化。
4月8日上午10点前，CEO提交用户调研报告初稿给班班。
