### ISSUE TITLE
180328 日报，早提交9：00，晚提交10：00

### ISSUE THREAD

**Issue by Rebecca19** [Rebecca19/FeiWenTianTuan#5]
现在大家开始分头作战啦，所以需要各自常更新进度和疑难点。每日22：00晚会后，松果开一个日报issue，提醒大家开会时提到的重点。大家可以在这里更新确认，自己设定完善目标，彼此了解新一天重点内容。

0328没开晚会，每个人更新进度。
具体如下：
1.宏玉：
1）.先用landingpage收集5个用户信息，辛苦@一锋 那边帮忙汇总。
2）.然后选择1-2个加微信投放问卷（建议直接拿问卷的问题微信聊，做好记录），重点了解用户的需求、职场痛点等
3）.选择1个用户面对面聊（问题见模块三https://shimo.im/sheet/SSfqpAkanCwijlg7/ ）

2.琼月：正在进行demo+landingpage的UI优化，需要完稿页的提纲，需要自己产品定位PPT的说明。

3.王澎：
今晚提交行业分析报告前半部分，@一锋 在帮忙制图。
需要@陈宏玉 一起作业 运营 @松果子 增补竞品信息。

4.泽华：demo优化，

5.一锋：landingpage优化。增加引导跳转的文案等。

6.松果：竞品信息，用户调研周四上午出。

——————————

昨日重点

1.王彭：今天只做了竞品分析。明天完善行业研究

2.宏玉：出一个用户调研方案（附上链接）。明天继续优化，并带大家做用户研究。明天，周三开始每位成员要开始找种子用户了，可以从公司实习生，二度人脉找起。完善趁早的竞品分析。

3.松果：提交项目管理，周三确定每一位成员都会使用本软件。完善橙子学院的竞品分析。

4.琼月：协助landing page 和产品demo的排版、UI设计等等，如果时间允许，可以做两个landingpage。

5.泽华：继续出demo

6.一锋：landing页完善

个人提交示例：
     `王彭`
     `+ [ ] 行业研究 （重点）`
     `+ [ ] 关心产品原型 （次重点）`
     `+ [ ] 其它紧急事项`

**Comment by Rebecca19** [comment]
## 王彭
+ [ ] 行业研究 （重点）
    + 难点：没有做过成熟的行业研究，需要摸索，求大腿
+ [ ] 关心产品原型 （次重点）
+ [ ] 其它紧急事项

**Comment by annyeat** [comment]
1.提交项目管理，今日确定每一位成员都会使用本软件。
没有用过的同学语音私聊。

2.完善橙子学院的竞品分析。
之前没有做过详细的竞品分析，重新学习行业调研模块课程，今天22：00之前完成迭代一版新的。
