### ISSUE TITLE
种子用户收集（需完善执行）

### ISSUE THREAD

**Issue by annyeat** [Rebecca19/FeiWenTianTuan#7]
1.种子用户调研流程如下，大家看下
2.关于调研问题集目前可能不够完善，请大家添加仍需要补充的问题

https://shimo.im/sheet/SSfqpAkanCwijlg7/F3u76/ 点击链接查看「种子用户的收集和调研」

0328更新：

1.大家请每人收集五个目标用户信息（0-3岁），共计30人。—— 周三晚12点 
2.选择1-2个用户完成调研问题集问题并记录    —— 周四中午12点
3.选择1个用户面对面访谈 —— 周四中午12点

** 我认为第一次需要重点调研明确用户需求

**Comment by Rebecca19** [comment]
提问：

+ 我们需要定量问卷吧？重复信息就不需要了。
+ 有什么一定要问的问题么？可否提供问题模板。
@dreamiechen

**Comment by annyeat** [comment]
需要一个调查问卷

**Comment by Rebecca19** [comment]
补充问题，供参考：

1.你平时会看ted、网易公开课等公开平台的课程进行学习吗？如果有人帮你精选挑出，你愿意嘛？
2.你喜欢什么样的学习方式，课程、书本、一对一咨询？
3.你平时的学习习惯是怎样的？每天会投入多少时间？
4.你现在清楚你急需提高的能力有哪些吗？
5.你观察身边成长快的伙伴都有什么特质，尤其是学习特质？
6.你今年有挑选决策学习课程嘛？基于什么考量做出决策。

- 自学
	- 自学了什么，什么情况下开始的
	- 尝试过什么提高学习效率、学习效果的方法
- 目前困惑
 - 比如职业选择、职场处事等
- 目前有哪些困惑/困境，打算怎么处理？

- 所参与课程学习的基本情况（**重点关注付费课程**）
	 - 课程主题、面对人群
	 - 价位、课时时长、课程跨度、学员规模
	 - 模式：线上/视频/幻灯/工作坊？
	 - 参与时间，参与原因
	- 效果
	 - 最后的效果 VS 自己加入课程时的预期？
	- 过程
	 - 自己的投入情况如何
		   - 课程要求每周投入时长
		   - 实际个人投入时长
	 - 完成度
		   - 过程中遇到的困难/自己的阻碍有哪些，对自己影响最大的是什么？
		   - 当时是怎么处理这个阻碍的？结果如何？
		   - **注意引导参与者情景重现**

**Comment by Rebecca19** [comment]
问卷信息：

 - 性别、年龄
  - 学历、专业
  - 工作基本信息
    - 工作年限、行业、职位、收入、日常工作时长
    - 通勤时长、一般几点下班、几点到家、通勤习惯
  - 学习基本信息
    - 过去半年平均每周用于自我提升的时长，接下来的意愿（增加/保存/减少？）
    - 过去半年平均每月用于自我提升的资金投入，接下来的意愿（增加/保存/减少？）
    - 输入习惯：
      - 常逛的网站有哪些？
      - 媒介：视频、音频、纸质书、电子书、朋友圈图文
    - 一般用什么搜索引擎（ google 还是 百度还是？）
    - 多久会对外发布一篇文章？

**Comment by Rebecca19** [comment]
## 参考资料

- [Never Ask What They Want — 3 Better Questions to Ask in User Interviews ](https://medium.com/user-research/never-ask-what-they-want-3-better-questions-to-ask-in-user-interviews-aeddd2a2101e#.3qopcr9x1)

**Comment by annyeat** [comment]
一、产品需求验证模块：

1.现在的工作你是否喜欢？如果不喜欢的话，你想做哪类的工作？

2.你觉得，在你想尝试的工作中，你缺少哪方面的经验或者能力？

3.你的领导或同事有没有对你否定过你的某个能力，比如说你逻辑思维不好，或者沟通能力不太行？这些能力是哪方面你自认为最急需提高的？

4.你目前在使用哪些在线学习平台？在学习过程中你认为解决了你哪些问题？有没有你仍然未解决的问题？

**Comment by z6811494** [comment]
关于优化landing page转化率的调研问题：
（只针对30-50自己拉来的种子用户，在发送完landing page二维码后直接询问）
1. landing page是否足够吸引你？吸引你的点在哪？
2. 浏览后是否愿意报名？如果不愿意，为什么？
