### ISSUE TITLE
landingpage的问题

### ISSUE THREAD

**Issue by annyeat** [Rebecca19/FeiWenTianTuan#8]
一锋：
同步一下landing page的进展：
1. 文案基于昨晚的版本做了小调整；图片下午琼月会做些优化；

2. 另外landing page是产品的第一道门面，我觉得需要一个估计landing page转化率的机制，比如在用户看到landing page的时候，先做一个对landing page的提问，
比如：“看完后你是否有意愿报名”“如果不愿意，原因是什么”之类的，不然这个东西的迭代空间很有限。

**Comment by z6811494** [comment]
优化landing page转化率的调研问题，供参考：
（只针对30-50自己拉来的种子用户，在发送完landing page二维码后直接询问）

1. landing page是否足够吸引你？吸引你的点在哪？
2. 浏览后是否愿意报名？如果不愿意，为什么？

目前我只能想到从用研部分来获取landing page的反馈，或许还有其他方法能解决。
